version: '3.4'

services:
  pakbus:
    image: ${DOCKER_REGISTRY-}pakbus
    build:
      context: .
      dockerfile: PakBus/Dockerfile
  sql-edge:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Zafar@1162014
      - MSSQL_PID=Developer
    ports:
      - '1433:1433'
